# Generated by Django 4.0.5 on 2022-06-14 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='category',
            field=models.CharField(choices=[('ANALISES', 'Análises'), ('PROGRAMACAO', 'Programação'), ('APRESENTACAO', 'Apresentação'), ('OUTROS', 'Outros')], max_length=15),
        ),
        migrations.AlterField(
            model_name='filme',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 17, 30, 50, 11918, tzinfo=utc)),
        ),
    ]
