# Generated by Django 4.0.5 on 2022-06-14 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_alter_filme_category_alter_filme_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 17, 30, 56, 76015, tzinfo=utc)),
        ),
    ]
